- src/elements/modal/Modal.js
- src/elements/modal/ModalPortal.js
- src/elements/modal/style.scss
Modal Componenet import 후 아래와 같이 사용할 수 있습니다.
```javascript
function Component() {
const [isOpenModal, setIsOpenModal] = useState(false);
...
// render
return <>
...
{isOpenModal && <Modal onClose={()=>setOpenModal(false)} content={<div>Hello, World?</div>} />}
</>
}
```
위 예시에서는 Modal content로 `<div>` 태그를 전달했지만 컴포넌트로 만들어서 전달하시는 걸 추천드립니다!  😎
> 김민주: <feature> Element Modal 추가

- public/index.html
- src/elements/modal/Modal.js
> 김민주: <fix> Modal error fix #4

- src/components/formSignUp/FormSignUp.jsx
- src/components/formSignUp/style.js
- src/hooks/useInput.js
- src/pages/SignUp.jsx
> 신혜정 : <Feature> signup 기능 구현 

- package.json
- src/components/formSignIn/FormSignIn.jsx
- src/components/googleLogin/GoogleLogin.jsx
- 로그인시 저장하는 토큰명 수정
- 구글 로그인 추가
> 신혜정 : <Feature/API> signin 수정

- src/components/videoroom/components/VideoRoomComponent.js
- src/components/videoroom/components/stream/OvVideo.js
- src/components/videoroom/components/stream/StreamComponent.js
- src/components/videoroom/components/toolbar/ToolbarComponent.js
- 버튼으로 제어하는 Mute 기능 작성
- Socket을 통해 제어 할 수 있도록 개선 필요함
> 김민주: <feature> #21 버튼으로 제어하는 Mute 기능 작성

- src/elements/modal/style.scss
> 김민주: <fix> Modal z-index 수정

- package.json
- src/components/chat/Chat.jsx
- src/components/chatRoom/ChatRoom.jsx
- src/components/chatRoomList/ChatRoomList.jsx
- src/components/formSignIn/FormSignIn.jsx
- src/elements/modal/style.scss
- src/pages/gameroom/GameRoom.jsx
- src/pages/gameroom/style.scss
- src/shared/Request.js
- [BE 채팅방 리스트 > 입장 > SockJs 및 Stomp 연결 방식]에서 [Game Room 입장 > SockJS 및 Stopm 연결 방식]으로 변경
> 김민주: <feature> gameroom 채팅 로직 변경

- src/components/videoroom/components/VideoRoomComponent.js
- src/components/videoroom/components/VideoRoomComponent.scss
- src/components/videoroom/components/stream/StreamComponent.js
- src/components/videoroom/components/stream/StreamComponent.scss
Game Room 내 Camera 들의 Layout. Figma 요청대로 수정완료
> 김민주: <style> GameRoom Camera layout 수정

- src/components/aRoom/ARoom.jsx
- src/components/roomList/RoomList.jsx
- src/components/roomList/style.scss
- src/pages/lobby/Lobby.jsx
- src/redux/modules/roomsSlice.js
- Roomlist API 연결
- paging
- Room Click 시 클릭한 룸 정보 redux 저장
> 김민주: <feature> RoomList API 연결

- src/components/gameTimer/GameTimer.jsx
- src/components/gameTimer/style.scss
- src/pages/gameroom/GameRoom.jsx
- #47 
- GameRoom에서 setTimer 함수를 통해 시간 지정 가능
> 김민주: <feature> GameTimer 

- src/App.js
- src/components/roomList/RoomList.jsx
#52
App.js 파일 내 service worker 관련 주석
RoomList.jsx 에서 optional chaining 적용
> 정건희: <fix> service worker 및 roomlist 조회 오류 수정

- src/components/videoroom/components/VideoRoomComponent.js
#52 
VideoRoomComponent.js 파일 내 사용하지 않는 모듈
> 정건희: <fix> VideoRoomComponent 사용하지 않는 모듈 주석

- src/components/gameBoard/GameBoard.jsx
- src/pages/gameroom/GameRoom.jsx
> 김민주: <fix> 한번 더 투표 / 라이어 투표 선택 websocket 연결

- src/components/gamePopup/GamePopup.jsx
- src/components/gamePopup/style.scss
> 김민주: <style> Game Popup

- src/components/roomList/RoomList.jsx
- src/components/roomList/style.scss
- src/images/svg/icArrowRight.svg
- src/pages/lobby/Lobby.jsx
> 신혜정 : <Style> lobby 스타일 수정

- src/components/videoroom/components/VideoRoomComponent.js
- src/components/videoroom/components/stream/StreamComponent.js
- src/components/videoroom/components/stream/StreamComponent.scss
> 김민주: <feature> video 아래 usernickname표시 및 spotlight 표시 오류 수정 #72 #73

- src/shared/Request.js
- instance 내 cookie에 저장된 token을 불러오는 기능 추가 / interceptor와 cookie 두가지 방식으로 Header에 token 추가
> 김민주: <fix> 새로고침 후 token 추가 error #77

- src/components/createRoomForm/style.scss
- src/components/roomList/style.scss
- src/pages/lobby/style.scss
- 방 만들기 모달 수정
- 게임방 입장하기 스타일 수정
> 신혜정 : <Style> 로비, 방 만들기, 게임방 입장하기 스타일 수정

- src/components/aRoom/ARoom.jsx
- src/pages/lobby/Lobby.jsx
- src/redux/modules/gameSlice.js
- 비디오/마이크가 있으나 getUserMedia 로 접근이 어려운 경우 ( 다른 브라우저에서 사용중인 경우 ) Open-vidu 접속불가 오류 발생
- 오류확인 시 방 접근이 어렵도록 차단
> 김민주: <fix> 비디오/마이크 접근 오류 시 게임룸 입장 차단

- src/components/gamePopup/GamePopup.jsx
- src/components/gamePopup/style.scss
- src/pages/gameroom/GameRoom.jsx
- src/redux/modules/gameSlice.js
- 다중 투표 막기
- 참가자 승리/ 라이어 승리 결과 멤버 정상화하기
- Spotlight Mute & Unmute 정상화
> 김민주: <fix> spotlight Mute & Unmute 테스트

- src/components/aRoom/ARoom.jsx
- src/pages/gameroom/GameRoom.jsx
- src/pages/lobby/Lobby.jsx
- Lobby에서는 실제 카메라 또는 마이크를 사용하지 않음에도 입장 제한을 위해 불필요한 디바이스 체크가 진행되어 이를 GameRoom 입장 직후로 변경
> 김민주: <feature> 게임룸 입장 전 디바이스 체크 Lobby > GameRoom 진입 직후로 변경

- src/components/createRoomForm/CreateRoomForm.jsx
- 방 제목 공란으로 입력불가 조건 설정
- 초기 방 설정 시 랜덤한 기본 방 제목 제공
> 김민주: <feature> 방제목 공란체크/기본 방제목

- src/components/createRoomForm/CreateRoomForm.jsx
- 기본 RoomName으로 방 생성 시 Input value로 인식하지 못하는 오류 수정
> 김민주: <fix> 초기 방제목 Input value로 인식 못하는 오류 수정

- src/components/roomList/RoomList.jsx
- src/components/roomList/style.scss
> 신혜정 : <Style> select박스 디자인 반영

- src/components/videoroom/video/Video.js
> 김민주: <fix> 왕관표시 오류 수정

- .gitignore
- src/components/sign/googleLogin/GoogleLogin.jsx
구글 로그인 성공 이후 로비 입장 redirection 수정
설정 코드 중 클라이언트 id 환경변수 추가
> 정건희: <fix> 구글 로그인

- src/components/community/communityCard/CommunityCard.jsx
- src/components/community/communityDetail/CommunityDetail.jsx
- src/components/community/communityFix/CommunityFix.jsx
- src/components/community/communityFix/style.scss
- src/components/community/communityList/CommunityList.jsx
- src/components/community/communityList/style.scss
- src/components/roomList/style.scss
-  Dropdown 메뉴 CSS 수정
- 수정 시 기존 내용 보이게 변경
- 수정 창 textarea로 변경
- 수정 취소하기 수정
- 본인 글이 아닌 경우 수정/삭제 보이지 않게 변경
- 수정 완료 이후 링크 수정
- 닉네임 #이후 지우기
- 삭제 이후 alert창 띄우기 + 랜딩 주소 바꾸기
- 검색 창 위치 수정
> 신혜정 : <feature> 게시판 기능 수정, 검색 기능 추가 등

- .gitignore
- src/components/createRoomForm/CreateRoomForm.jsx
- src/components/lobbyHeader/LobbyHeader.jsx
- src/components/lobbyHeader/style.scss
- src/components/socialHeader/SocialHeader.jsx
- src/components/socialHeader/style.scss
- src/pages/lobby/style.scss
로비 배경화면 css 정리 및 추가 / object-fit: cover
로비, 소셜 헤더바 텍스트 정렬 css 정리 및 수정
.gitignore 내 .env 중복 코드 삭제
방만들기 제목 공백 예외처리 코드 수정 (띄어쓰기 포함)
> 정건희: <style> Lobby 배경화면, 헤더 css 수정

- src/components/myPage/myPageForm/MyPageForm.jsx
- src/components/myPage/myPageRecord/MyPageRecord.jsx
- 전적을 조회할 때, 서버에서 받아오는 플레이 시간을
초기 값으로 받게 되면 조건문을 사용해 '0분'으로 보여주게 수정함
> 정건희: <feature> 마이페이지 플레이 시간 style 수정

- src/components/gamePopup/style.scss
- 게임룸 닉네임 길이 초과시 줄 바꿈 금지 설정 (css)
> 신혜정 : <style> GameRoom 닉네임 줄 바꿈 금지 설정

- src/pages/lobby/style.scss
- 배경화면 아래로 묻힌 방 조회 z-index 속성 수정
- 마이페이지 모달 위로 보이는 방 만들기 버튼 z-index 속성 수정
> 정건희: <fix> Lobby css 수정

- src/components/chat/style.scss
> 정건희: <style> chat 스크롤 바 css 적용

- src/components/aRoom/ARoom.jsx
- src/components/aRoom/style.scss
- src/components/createRoomForm/style.scss
- src/components/lobbyHeader/style.scss
- src/components/roomList/RoomList.jsx
- src/components/roomList/style.scss
- src/components/socialHeader/style.scss
- src/pages/lobby/Lobby.jsx
- src/pages/lobby/style.scss
- 게임모드, 방 제목, 비밀번호 폰트 수정 ( 크기 및 종류 )
- 방 만들기 모달 버튼 피그마 컬러에 맞게 수정
> 정건희: <style> Lobby 폰트 및 간격 css 수정 적용

- src/components/community/communityList/CommunityList.jsx
- src/components/roomList/RoomList.jsx
- src/components/roomList/style.scss
-  select 를 ul로 변경
- option을 li로 변경
- 피그마 스타일 적용
> 신혜정 : <Style> lobby 드롭 박스 메뉴 스타일 적용

- src/components/community/communityList/CommunityList.jsx
-  일치하는 검색 결과가 없을 시 >> (검색 결과에 맞는 게시글이 존재하지 않습니다. )가 얼럿에 출력되도록 수정
> 신혜정 : <Fix> search 에러 얼럿 수정

- src/components/community/communityWrite/CommunityWrite.jsx
> 김민주: <fix> 게시글 공란으로 작성이 불가하도록 예외처리

- src/pages/gameroom/GameRoom.jsx
- src/redux/modules/gameSlice.js
- src/redux/modules/roomsSlice.js
> 김민주: <feature> 게임 중 나간 경우 예외처리

- src/components/community/communityList/style.scss
- src/components/roomList/RoomList.jsx
- src/components/roomList/style.scss
> 정건희: <style> Lobby 드롭 박스 위치 정렬 수정

- src/shared/Request.js
> 김민주: <fix> 로그아웃/탈퇴 후 instance header 변경되지 않는 오류 수정

- src/pages/gameroom/GameRoom.jsx
> 김민주: <feature> 게임 시작 인원 제한

- src/components/comments/commentItem/CommentItem.jsx
- src/components/comments/commentPost/CommentPost.jsx
- src/components/community/communityCard/CommunityCard.jsx
- src/components/community/communityDetail/CommunityDetail.jsx
- src/components/community/communityFix/CommunityFix.jsx
- src/components/community/communityList/CommunityList.jsx
- src/components/community/communityWrite/CommunityWrite.jsx
> 정건희: <fix> 댓글 수정

- src/pages/gameroom/GameRoom.jsx
> 김민주: <fix> 브라우저 종료 시 leaveRoom API 호출되지않는 오류 수정

- src/components/videoroom/video/Video.js
- src/components/videoroom/videoRoom/VideoRoom.js
- src/components/videoroom/videoRoom/userModel.js
- src/pages/gameroom/GameRoom.jsx
- 사용하지 않는 함수 정리
- boolean변수명 active로 true/false의미 동일하게 변경
> 김민주: <refactor> videoroom 함수정리/변수명통일

- src/components/videoroom/videoRoom/VideoRoom.js
- src/components/videoroom/videoRoom/style.scss
- src/pages/gameroom/GameRoom.jsx
- src/pages/gameroom/style.scss
- Mic&Video Icon모양과 실제 Mic&Video 출력 상태가 다른 오류 수정
> 김민주: <fix> mic & Cam Icon

- src/components/videoroom/videoRoom/VideoRoom.js
- src/pages/gameroom/GameRoom.jsx
- Device Loading 중 Mic/Video 조작 시 오류 발생하여 streammanager 로딩 전 조작되지 않게끔 변경
- Video 차단 시 접속 불가하도록 변경
- gameroom 내 getDevice 비동기 예외처리 추가
> 김민주: <fix> Device loading 처리

- src/pages/gameroom/GameRoom.jsx
> 김민주: <fix> 입장 후 Owner 정보 표시 오류 수정

- src/pages/gameroom/GameRoom.jsx
- Lier에 걸렸을 때 board 내 시민 문구가 뜨는 표시오류 수정
> 김민주: <fix> Liar Board 내용 표시 오류 수정

- src/components/gameBoard/GameBoard.jsx
- 배포서버에서 다수 테스트 시 바보모드일 때 보드 오류 확인되어 수정
> 김민주: <fix> 바보모드 라이어일 때 오류 수정

- src/components/myPage/myPageSignOut/MyPageSignOut.jsx
> 김민주: <fix> 회원탈퇴 시 헤더가 전달되지 않는 오류 수정

- src/components/myPage/myPageSignOff/MyPageSignOff.jsx
- src/components/myPage/myPageSignOut/MyPageSignOut.jsx
> 김민주: <fix> 구글 회원탈퇴 오류 수정

- src/components/gameBoard/GameBoard.jsx
- src/pages/gameroom/GameRoom.jsx
- Issue : #234 
- 한번더/투표하기 방장 선택 중 다른 유저에게 멘트 추가
- 게임 도중 유저가 퇴장할 경우 WAIT_JOIN Board가 출력되는 오류 수정
> 김민주: <fix> Gameboard 수정

- src/components/roomList/RoomList.jsx
- src/components/roomList/style.scss
- 생성된 방이 없을 경우 > 로비에서 생성된 방이 없습니다. 문구 추가
> 정건희: <style> 생성된 방이 없습니다. 문구 추가

- src/components/videoroom/video/Video.js
- src/components/videoroom/video/style.scss
- 쌓임맥락 변경 : 캐릭터 이미지 또는 비디오 / 왕관 / 뮤트 / 레디 ( 아래 → 위 순서로 변경 ) 
- 다른 유저의 Mic Mute 정보도 비디오 레이아웃 내 표시되도록 수정
> 김민주: <fix> 비디오 레이아웃 수정

- src/components/gameRuleBoard/GameRuleBoard.jsx
- src/components/lobbyHeader/LobbyHeader.jsx
- src/components/socialHeader/SocialHeader.jsx
- 게임 룰 버튼 클릭 이벤트를 물음표 아이콘에서 > 버튼으로 수정
> 정건희: <fix> 게임 룰 버튼 클릭 영역 수정

- src/components/roomList/RoomList.jsx
- src/components/roomList/style.scss
> 김민주: <fix> 필터 변경 시 페이지 초기화 되지 않아 발생하는 출력오류 수정
